name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: Babyfingerss
          outputs: dist/snake.svg

      # Upload Snake Animation
      - name: Upload Snake Animation
        run: |
          mkdir -p output
          mv dist/snake.svg output/github-snake.svg
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/github-snake.svg
          git commit -m "Generated Snake Animation"
          git push origin output
